"""add scalable list indexes

Revision ID: 6bf60953b28f
Revises: 7332ed65ba00
Create Date: 2026-03-30 14:58:52.485001

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '6bf60953b28f'
down_revision = '7332ed65ba00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index('ix_activity_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_activity_risk_score', ['risk_score'], unique=False)
        batch_op.create_index('ix_activity_sla_deadline', ['sla_deadline'], unique=False)
        batch_op.create_index('ix_activity_type_created_at', ['activity_type', 'created_at'], unique=False)

    with op.batch_alter_table('consumables', schema=None) as batch_op:
        batch_op.create_index('ix_consumable_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_user_created_at', ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_user_created_at')

    with op.batch_alter_table('consumables', schema=None) as batch_op:
        batch_op.drop_index('ix_consumable_created_at')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_type_created_at')
        batch_op.drop_index('ix_activity_sla_deadline')
        batch_op.drop_index('ix_activity_risk_score')
        batch_op.drop_index('ix_activity_created_at')

    # ### end Alembic commands ###
